name: .NET Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  variables:
    runs-on: ubuntu-latest
    name: Create variables
    outputs:
      istag: ${{ steps.vars.outputs.is_tag }}
      ref: ${{ steps.vars.outputs.ref }}

    steps:

      - id: vars
        run: |
          echo "ref=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "is_tag=${{ startsWith(github.ref, 'refs/tags/') }}" >> $GITHUB_OUTPUT

  build-and-test:
    runs-on: ${{ matrix.os }}
    needs: variables

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

      - name: Build
        if: needs.variables.outputs.istag == 'false'
        run: dotnet build --configuration Release --no-restore -p:TreatWarningsAsErrors=true

      - name: Build with version ${{ needs.variables.outputs.ref }}
        if: needs.variables.outputs.istag == 'true'
        run: dotnet build --configuration Release -p:TreatWarningsAsErrors=true -p:Version=${{ needs.variables.outputs.ref }} -p:PackageVersion=${{ needs.variables.outputs.ref }}

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - uses: actions/upload-artifact@v3
        if: needs.variables.outputs.istag == 'true'
        with:
          name: nuget-package
          path: FilteredList/bin/Release/*.nupkg
